export const orders = [
  {
    id: "f7ca045d-19bf-4dff8d-a4da-f3369fabce42",
    idCustomer: "kh1",
    customerName: "Nguyễn Quốc Hưng",
    phone: "0981234567",
    address: "345 Thạch Bàn, Long Biên ",
    products: [
      {
        id: "p3",
        name: "Bắp cải tím",
        type: "vegetable",
        src: "/images/bapCaiTim.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 2,
      },
      {
        id: "p15",
        name: "Cam vàng Úc",
        type: "fruit",
        src: "/images/camVangUc.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 3,
      },
      {
        id: "p23",
        name: "Đậu Cove",
        type: "vegetable",
        src: "/images/dauCove.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 3,
      },
    ],
    total: 3800000,
    status: 4,
  },
  {
    id: "72b369dd01-6c44-4a3b-95fa-b2db161d75e4",
    idCustomer: "kh2",
    customerName: "Nguyễn Văn Long",
    phone: "0891234567",
    address: "146 Vương Thừa Vũ",
    products: [
      {
        id: "p62",
        name: "Gạo tẻ",
        type: "rice",
        src: "/images/gao.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 2,
      },

      {
        id: "p22",
        name: "Củ đậu",
        type: "fruit",
        src: "/images/cuDau.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 3,
      },
    ],
    total: 3325000,
    status: 3,
  },
  {
    id: "86ddeb52ee2-ec91-41c4-9f84-17e830485c19",
    idCustomer: "kh3",
    customerName: "Đinh Thị Thanh Tâm",
    phone: "1239324234",
    address: "234 Cầu Giấy, Hà Nội",
    products: [
      {
        id: "p3",
        name: "Bắp cải tím",
        type: "vegetable",
        src: "/images/bapCaiTim.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 1,
      },
      {
        id: "p8",
        name: "Cà chua",
        type: "vegetable",
        src: "/images/caChua.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 1,
      },
      {
        id: "p16",
        name: "Cần tây",
        type: "vegetable",
        src: "/images/canTay.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 1,
      },
      {
        id: "p32",
        name: "Hành tây",
        type: "vegetable",
        src: "/images/hanhTay.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 2,
      },
      {
        id: "p33",
        name: "Hạt sen",
        type: "vegetable",
        src: "/images/hatSen.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 1,
      },
    ],
    total: 2850000,
    status: 2,
  },
  {
    id: "0612b0ab-7979-4c0f-9ee83f-60ee5e6590dd",
    idCustomer: "kh1",
    customerName: "Nguyễn Thanh Hưng",
    phone: "34324141",
    address: "345 Dịch Vọng Hậu",
    products: [
      {
        id: "p4",
        name: "Bí đỏ",
        type: "vegetable",
        src: "/images/biDo.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 1,
      },
      {
        id: "p9",
        name: "Cải cúc",
        type: "vegetable",
        src: "/images/caiCuc.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 1,
      },
    ],
    total: 950000,
    status: 1,
  },
  {
    id: "f7ca045d-19bf-rre4d8d-a4da-f3369fabce42",
    idCustomer: "kh1",
    customerName: "Nguyễn Quốc Hưng",
    phone: "0981234567",
    address: "345 Thạch Bàn, Long Biên ",
    products: [
      {
        id: "p3",
        name: "Bắp cải tím",
        type: "vegetable",
        src: "/images/bapCaiTim.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 2,
      },
      {
        id: "p15",
        name: "Cam vàng Úc",
        type: "fruit",
        src: "/images/camVangUc.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 3,
      },
      {
        id: "p23",
        name: "Đậu Cove",
        type: "vegetable",
        src: "/images/dauCove.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 3,
      },
    ],
    total: 3800000,
    status: 4,
  },
  {
    id: "72b36gg901-6c44-4a3b-95fa-b2db161d75e4",
    idCustomer: "kh2",
    customerName: "Nguyễn Văn Long",
    phone: "0891234567",
    address: "146 Vương Thừa Vũ",
    products: [
      {
        id: "p62",
        name: "Gạo tẻ",
        type: "rice",
        src: "/images/gao.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 2,
      },

      {
        id: "p22",
        name: "Củ đậu",
        type: "fruit",
        src: "/images/cuDau.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 3,
      },
    ],
    total: 3325000,
    status: 3,
  },
  {
    id: "cc86ddeb52-ec91-41c4-9f84-17e830485c19",
    idCustomer: "kh3",
    customerName: "Đinh Thị Thanh Tâm",
    phone: "1239324234",
    address: "234 Cầu Giấy, Hà Nội",
    products: [
      {
        id: "p3",
        name: "Bắp cải tím",
        type: "vegetable",
        src: "/images/bapCaiTim.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 1,
      },
      {
        id: "p8",
        name: "Cà chua",
        type: "vegetable",
        src: "/images/caChua.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 1,
      },
      {
        id: "p16",
        name: "Cần tây",
        type: "vegetable",
        src: "/images/canTay.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 1,
      },
      {
        id: "p32",
        name: "Hành tây",
        type: "vegetable",
        src: "/images/hanhTay.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 2,
      },
      {
        id: "p33",
        name: "Hạt sen",
        type: "vegetable",
        src: "/images/hatSen.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 1,
      },
    ],
    total: 2850000,
    status: 2,
  },
  {
    id: "0612b0ab-7979-4c0f-983f-60ee5te6590dd",
    idCustomer: "kh1",
    customerName: "Nguyễn Thanh Hưng",
    phone: "34324141",
    address: "345 Dịch Vọng Hậu",
    products: [
      {
        id: "p4",
        name: "Bí đỏ",
        type: "vegetable",
        src: "/images/biDo.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 1,
      },
      {
        id: "p9",
        name: "Cải cúc",
        type: "vegetable",
        src: "/images/caiCuc.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 1,
      },
    ],
    total: 950000,
    status: 1,
  },
  {
    id: "fr7ca045d-19bf-4d8d-a4da-f3369fabce42",
    idCustomer: "kh1",
    customerName: "Nguyễn Quốc Hưng",
    phone: "0981234567",
    address: "345 Thạch Bàn, Long Biên ",
    products: [
      {
        id: "p3",
        name: "Bắp cải tím",
        type: "vegetable",
        src: "/images/bapCaiTim.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 2,
      },
      {
        id: "p15",
        name: "Cam vàng Úc",
        type: "fruit",
        src: "/images/camVangUc.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 3,
      },
      {
        id: "p23",
        name: "Đậu Cove",
        type: "vegetable",
        src: "/images/dauCove.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 3,
      },
    ],
    total: 3800000,
    status: 4,
  },
  {
    id: "72b36901-6rrc44-4a3b-95fa-b2db161d75e4",
    idCustomer: "kh2",
    customerName: "Nguyễn Văn Long",
    phone: "0891234567",
    address: "146 Vương Thừa Vũ",
    products: [
      {
        id: "p62",
        name: "Gạo tẻ",
        type: "rice",
        src: "/images/gao.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 2,
      },

      {
        id: "p22",
        name: "Củ đậu",
        type: "fruit",
        src: "/images/cuDau.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 3,
      },
    ],
    total: 3325000,
    status: 3,
  },
  {
    id: "86ddeb52-ec91-41c4-9f8224-17e830485c19",
    idCustomer: "kh3",
    customerName: "Đinh Thị Thanh Tâm",
    phone: "1239324234",
    address: "234 Cầu Giấy, Hà Nội",
    products: [
      {
        id: "p3",
        name: "Bắp cải tím",
        type: "vegetable",
        src: "/images/bapCaiTim.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 1,
      },
      {
        id: "p8",
        name: "Cà chua",
        type: "vegetable",
        src: "/images/caChua.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 1,
      },
      {
        id: "p16",
        name: "Cần tây",
        type: "vegetable",
        src: "/images/canTay.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 1,
      },
      {
        id: "p32",
        name: "Hành tây",
        type: "vegetable",
        src: "/images/hanhTay.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 2,
      },
      {
        id: "p33",
        name: "Hạt sen",
        type: "vegetable",
        src: "/images/hatSen.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 1,
      },
    ],
    total: 2850000,
    status: 2,
  },
  {
    id: "0612b0ab-7979-efw4c0f-983f-60ee5e6590dd",
    idCustomer: "kh1",
    customerName: "Nguyễn Thanh Hưng",
    phone: "34324141",
    address: "345 Dịch Vọng Hậu",
    products: [
      {
        id: "p4",
        name: "Bí đỏ",
        type: "vegetable",
        src: "/images/biDo.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 1,
      },
      {
        id: "p9",
        name: "Cải cúc",
        type: "vegetable",
        src: "/images/caiCuc.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 1,
      },
    ],
    total: 950000,
    status: 1,
  },
  {
    id: "f7ca04ưv5d-19bf-4d8d-a4da-f3369fabce42",
    idCustomer: "kh1",
    customerName: "Nguyễn Quốc Hưng",
    phone: "0981234567",
    address: "345 Thạch Bàn, Long Biên ",
    products: [
      {
        id: "p3",
        name: "Bắp cải tím",
        type: "vegetable",
        src: "/images/bapCaiTim.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 2,
      },
      {
        id: "p15",
        name: "Cam vàng Úc",
        type: "fruit",
        src: "/images/camVangUc.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 3,
      },
      {
        id: "p23",
        name: "Đậu Cove",
        type: "vegetable",
        src: "/images/dauCove.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 3,
      },
    ],
    total: 3800000,
    status: 4,
  },
  {
    id: "72b36901-6c44-4a3b-95fdfa-b2db161d75e4",
    idCustomer: "kh2",
    customerName: "Nguyễn Văn Long",
    phone: "0891234567",
    address: "146 Vương Thừa Vũ",
    products: [
      {
        id: "p62",
        name: "Gạo tẻ",
        type: "rice",
        src: "/images/gao.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 2,
      },

      {
        id: "p22",
        name: "Củ đậu",
        type: "fruit",
        src: "/images/cuDau.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 3,
      },
    ],
    total: 3325000,
    status: 3,
  },
  {
    id: "86ddeb52-ec91-41c4f-9f84-17e830485c19",
    idCustomer: "kh3",
    customerName: "Đinh Thị Thanh Tâm",
    phone: "1239324234",
    address: "234 Cầu Giấy, Hà Nội",
    products: [
      {
        id: "p3",
        name: "Bắp cải tím",
        type: "vegetable",
        src: "/images/bapCaiTim.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 1,
      },
      {
        id: "p8",
        name: "Cà chua",
        type: "vegetable",
        src: "/images/caChua.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 1,
      },
      {
        id: "p16",
        name: "Cần tây",
        type: "vegetable",
        src: "/images/canTay.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 1,
      },
      {
        id: "p32",
        name: "Hành tây",
        type: "vegetable",
        src: "/images/hanhTay.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 2,
      },
      {
        id: "p33",
        name: "Hạt sen",
        type: "vegetable",
        src: "/images/hatSen.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 1,
      },
    ],
    total: 2850000,
    status: 2,
  },
  {
    id: "0612b0abdf-7979-4c0f-983f-60ee5e6590dd",
    idCustomer: "kh1",
    customerName: "Nguyễn Thanh Hưng",
    phone: "34324141",
    address: "345 Dịch Vọng Hậu",
    products: [
      {
        id: "p4",
        name: "Bí đỏ",
        type: "vegetable",
        src: "/images/biDo.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 1,
      },
      {
        id: "p9",
        name: "Cải cúc",
        type: "vegetable",
        src: "/images/caiCuc.jpg",
        price: 500000,
        discount: 5,
        remains: 5000,
        quantity: 1,
      },
    ],
    total: 950000,
    status: 1,
  },
]
