import { v4 } from "uuid"

export const tubersList = [
  {
    id: v4(),
    src: "/img/cuQua/biDo.jpg",
    name: "Bí đỏ",
    discount: 0,
    price: 523000,
    remains: 500,
  },
  {
    id: v4(),
    src: "/img/cuQua/biDoDai.jpg",
    name: "Bí đỏ Hải Dương",
    discount: 0,
    price: 10000,
    remains: 0,
  },
  {
    id: v4(),
    src: "/img/cuQua/caChua.jpg",
    name: "Cà chua",
    discount: 0,
    price: 9000,
    remains: 540,
  },
  {
    id: v4(),
    src: "/img/cuQua/caTim.jpg",
    name: "Cà tím",
    discount: 11,
    price: 87000,
    remains: 0,
  },
  {
    id: v4(),
    src: "/img/cuQua/cuDau.jpg",
    name: "Củ đậu",
    discount: 5,
    price: 96000,
    remains: 520,
  },
  {
    id: v4(),
    src: "/img/cuQua/dauCove.jpg",
    name: "Đậu Cove",
    discount: 5,
    price: 20000,
    remains: 510,
  },
  {
    id: v4(),
    src: "/img/cuQua/gungCu.jpg",
    name: "Gừng củ",
    discount: 50,
    price: 67000,
    remains: 10,
  },
  {
    id: v4(),
    src: "/img/cuQua/hanhCuHD.jpg",
    name: "Hành củ Hưng Yên",
    discount: 23,
    price: 56000,
    remains: 0,
  },
  {
    id: v4(),
    src: "/img/cuQua/hanhTay.jpg",
    name: "Hành tây",
    discount: 33,
    price: 400000,
    remains: 50,
  },
  {
    id: v4(),
    src: "/img/cuQua/hatSen.jpg",
    name: "Hạt sen",
    discount: 0,
    price: 94000,
    remains: 0,
  },
  {
    id: v4(),
    src: "/img/cuQua/khoaiLang.jpg",
    name: "Khoai lang",
    discount: 11,
    price: 43000,
    remains: 50,
  },
  {
    id: v4(),
    src: "/img/cuQua/muopDang.jpg",
    name: "Mướp đắng",
    discount: 0,
    price: 69000,
    remains: 50,
  },
  {
    id: v4(),
    src: "/img/cuQua/ngo.jpg",
    name: "Ngô",
    discount: 0,
    price: 34000,
    remains: 50,
  },
  {
    id: v4(),
    src: "/img/cuQua/otChuong.jpg",
    name: "Ớt chuông Đà Lạt",
    discount: 0,
    price: 106000,
    remains: 50,
  },
  {
    id: v4(),
    src: "/img/cuQua/otMau.jpg",
    name: "Ớt Nhật",
    discount: 0,
    price: 90000,
    remains: 50,
  },
  {
    id: v4(),
    src: "/img/cuQua/otNgot.jpg",
    name: "Ớt ngọt",
    discount: 10,
    price: 10000,
    remains: 50,
  },
  {
    id: v4(),
    src: "/img/cuQua/otNho.jpg",
    name: "Ớt cay",
    discount: 0,
    price: 103000,
    remains: 50,
  },
  {
    id: v4(),
    src: "/img/cuQua/quaBau.jpg",
    name: "Quả bầu",
    discount: 0,
    price: 10000,
    remains: 50,
  },
  {
    id: v4(),
    src: "/img/cuQua/toiCu.jpg",
    name: "Tỏi củ",
    discount: 0,
    price: 123000,
    remains: 50,
  },
]
