export const users = [
  {
    id: "kh1",
    username: "kh1",
    password: "kh1",
    role: 4,
    name: "Nguyễn Văn Hưng",
  },
  {
    id: "kh2",
    username: "kh2",
    password: "kh2",
    role: 4,
    name: "Trần Hưng Đạo",
  },
  {
    id: "kh3",
    username: "kh3",
    password: "kh3",
    role: 4,
    name: "Lý Thường Kiệt",
  },
  {
    id: "nv1",
    username: "nv1",
    password: "nv1",
    role: 2,
    name: "Phạm Thị Thanh Tâm",
  },
  {
    id: "nv2",
    username: "nv2",
    password: "nv2",
    role: 3,
    name: "Nguyễn Văn A",
  },
  {
    id: "nv3",
    username: "nv3",
    password: "nv3",
    role: 2,
    name: "Thomas Anders",
  },
  {
    id: "nv4",
    username: "nv4",
    password: "nv4",
    role: 3,
    name: "Brother Louie",
  },
  {
    id: "nv5",
    username: "nv5",
    password: "nv5",
    role: 2,
    name: "Bigbang Nguyễn",
  },
  {
    id: "nv6",
    username: "nv6",
    password: "nv6",
    role: 3,
    name: "C. Ronaldo",
  },
  {
    id: "admin1",
    username: "admin1",
    password: "admin1",
    role: 1,
    name: "Hồ Ngọc Trung",
  },
]
